default:
  # 日志输出级别, DEBUG: 10, INFO: 20, WARNING: 30, ERROR: 40, CRITICAL: 50
  LOGGING_LEVEL: 10
  # 日志格式
  LOGGING_FORMAT: "[%(asctime)s] [%(name)s:%(lineno)d] %(levelname)s: %(message)s"
dev:
test:
prod:
